name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability. 
version: 3.2.0
homepage: https://github.com/csdcorp/speech_to_text

publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface:
    git:
      url: https://github.com/AhmedNourJamalElDin/speech_to_text.git
      path: speech_to_text_platform_interface
      ref: upgrade-flutter
  json_annotation: ^4.0.0
  clock: ^1.1.0
  pedantic: ^1.11.0
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  fake_async: ^1.2.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart
